apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-app
    type: front-end
  ports:
    - port: 9004
      targetPort: 80
      nodePort: 30011
